import './settings';
import './resetgame';
import './mapnavigation';
import './fullscreenmode';
import './togglebackground';
import './clearfactories';
import './showefficiency';
import './exportfactories';
import './clearcloud';